// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiniSupermarket.API.Data;

#nullable disable

namespace MiniSupermarket.API.Migrations
{
    [DbContext(typeof(SupermarketDbContext))]
    [Migration("20261008112257_AddCustomerAddress")]
    partial class AddCustomerAddress
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MiniSupermarket.API.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Bánh kẹo & Đồ ăn vặt",
                            Description = "Snack, bánh quy, kẹo dẻo, socola"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Nước giải khát & Trà",
                            Description = "Nước ngọt, nước khoáng, trà xanh, nước tăng lực"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Sữa & Sản phẩm từ sữa",
                            Description = "Sữa tươi, sữa chua, sữa đặc, phô mai"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Mì gói & Thực phẩm ăn liền",
                            Description = "Mì ăn liền, phở khô, cháo gói, miến ăn liền"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Gia vị & Nước chấm",
                            Description = "Nước mắm, hạt nêm, đường, muối, bột ngọt, tiêu"
                        },
                        new
                        {
                            CategoryId = 6,
                            CategoryName = "Dầu ăn & Bơ",
                            Description = "Dầu thực vật, dầu mè, bơ thực vật, dầu hào"
                        },
                        new
                        {
                            CategoryId = 7,
                            CategoryName = "Gạo, Bột & Nông sản khô",
                            Description = "Gạo thơm, bột mì, bột chiên giòn, nếp, đậu xanh"
                        },
                        new
                        {
                            CategoryId = 8,
                            CategoryName = "Đồ hộp & Thực phẩm chế biến",
                            Description = "Cá hộp, pate, thịt hộp, xúc xích tiệt trùng"
                        },
                        new
                        {
                            CategoryId = 9,
                            CategoryName = "Hóa phẩm giặt xả & Tẩy rửa",
                            Description = "Nước giặt, nước xả vải, nước rửa chén, nước lau sàn"
                        },
                        new
                        {
                            CategoryId = 10,
                            CategoryName = "Chăm sóc cá nhân & Vệ sinh",
                            Description = "Dầu gội, sữa tắm, kem đánh răng, xà bông cục"
                        },
                        new
                        {
                            CategoryId = 11,
                            CategoryName = "Giấy ăn & Khăn ướt",
                            Description = "Giấy vệ sinh, khăn ăn, khăn giấy ướt, tã bỉm"
                        },
                        new
                        {
                            CategoryId = 12,
                            CategoryName = "Đồ dùng gia đình & Nhà bếp",
                            Description = "Màng bọc thực phẩm, túi rác, miếng cọ rửa, tăm bông"
                        },
                        new
                        {
                            CategoryId = 13,
                            CategoryName = "Cà phê, Trà & Đồ uống hòa tan",
                            Description = "Cà phê hòa tan, trà túi lọc, trà atiso, ngũ cốc dinh dưỡng"
                        },
                        new
                        {
                            CategoryId = 14,
                            CategoryName = "Văn phòng phẩm & Tiện ích",
                            Description = "Bút viết, tập vở, kéo, băng keo, phong bì, bấm móng tay"
                        },
                        new
                        {
                            CategoryId = 15,
                            CategoryName = "Thực phẩm đông lạnh & Mát",
                            Description = "Kem cây, xúc xích tươi, lạp xưởng, chả lụa"
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MembershipRank")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("RewardPoints")
                        .HasColumnType("int");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            Address = "33B đường 42, phường Bình Trưng Đông, Thủ Đức, TP.HCM",
                            CustomerName = "Nguyễn Văn A",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0901122334",
                            RewardPoints = 150
                        },
                        new
                        {
                            CustomerId = 2,
                            Address = "33B đường 42, phường Bình Trưng Đông, Thủ Đức, TP.HCM",
                            CustomerName = "Trần Thị B",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0918877665",
                            RewardPoints = 50
                        },
                        new
                        {
                            CustomerId = 3,
                            Address = "33B đường 42, phường Bình Trưng Đông, Thủ Đức, TP.HCM",
                            CustomerName = "Lê Văn C",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0983344556",
                            RewardPoints = 10
                        },
                        new
                        {
                            CustomerId = 4,
                            Address = "33B đường 42, phường Bình Trưng Đông, Thủ Đức, TP.HCM",
                            CustomerName = "Phạm Thị Dung",
                            MembershipRank = "Kim Cương",
                            PhoneNumber = "0978123456",
                            RewardPoints = 320
                        },
                        new
                        {
                            CustomerId = 5,
                            Address = "33B đường 42, phường Bình Trưng Đông, Thủ Đức, TP.HCM",
                            CustomerName = "Hoàng Văn Em",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0912345678",
                            RewardPoints = 180
                        },
                        new
                        {
                            CustomerId = 6,
                            Address = "33B đường 42, phường Bình Trưng Đông, Thủ Đức, TP.HCM",
                            CustomerName = "Vũ Thị Giang",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0966789012",
                            RewardPoints = 75
                        },
                        new
                        {
                            CustomerId = 7,
                            Address = "33B đường 42, phường Bình Trưng Đông, Thủ Đức, TP.HCM",
                            CustomerName = "Đỗ Minh Hùng",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0933221144",
                            RewardPoints = 20
                        },
                        new
                        {
                            CustomerId = 8,
                            Address = "33B đường 42, phường Bình Trưng Đông, Thủ Đức, TP.HCM",
                            CustomerName = "Đinh Thị Lan",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0944556677",
                            RewardPoints = 140
                        },
                        new
                        {
                            CustomerId = 9,
                            Address = "33B đường 42, phường Bình Trưng Đông, Thủ Đức, TP.HCM",
                            CustomerName = "Bùi Quang Mai",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0988990011",
                            RewardPoints = 60
                        },
                        new
                        {
                            CustomerId = 10,
                            Address = "33B đường 42, phường Bình Trưng Đông, Thủ Đức, TP.HCM",
                            CustomerName = "Trịnh Công Nam",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0909123890",
                            RewardPoints = 15
                        },
                        new
                        {
                            CustomerId = 11,
                            Address = "33B đường 42, phường Bình Trưng Đông, Thủ Đức, TP.HCM",
                            CustomerName = "Ngô Thị Oanh",
                            MembershipRank = "Kim Cương",
                            PhoneNumber = "0919283746",
                            RewardPoints = 450
                        },
                        new
                        {
                            CustomerId = 12,
                            Address = "33B đường 42, phường Bình Trưng Đông, Thủ Đức, TP.HCM",
                            CustomerName = "Phan Thành Phúc",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0977345678",
                            RewardPoints = 190
                        },
                        new
                        {
                            CustomerId = 13,
                            Address = "33B đường 42, phường Bình Trưng Đông, Thủ Đức, TP.HCM",
                            CustomerName = "Lý Thu Quỳnh",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0938475610",
                            RewardPoints = 85
                        },
                        new
                        {
                            CustomerId = 14,
                            Address = "33B đường 42, phường Bình Trưng Đông, Thủ Đức, TP.HCM",
                            CustomerName = "Võ Văn Sơn",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0908765432",
                            RewardPoints = 30
                        },
                        new
                        {
                            CustomerId = 15,
                            Address = "33B đường 42, phường Bình Trưng Đông, Thủ Đức, TP.HCM",
                            CustomerName = "Dương Thị Tuyết",
                            MembershipRank = "Kim Cương",
                            PhoneNumber = "0987654321",
                            RewardPoints = 500
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Barcode = "893456789001",
                            CategoryId = 1,
                            Price = 7000m,
                            ProductName = "Snack Oishi Cay 42g",
                            StockQuantity = 100
                        },
                        new
                        {
                            ProductId = 2,
                            Barcode = "893456789002",
                            CategoryId = 2,
                            Price = 10000m,
                            ProductName = "Nước ngọt Coca-Cola 320ml",
                            StockQuantity = 120
                        },
                        new
                        {
                            ProductId = 3,
                            Barcode = "893456789003",
                            CategoryId = 3,
                            Price = 9000m,
                            ProductName = "Sữa tươi tiệt trùng Vinamilk 180ml",
                            StockQuantity = 80
                        },
                        new
                        {
                            ProductId = 4,
                            Barcode = "893456789004",
                            CategoryId = 4,
                            Price = 4500m,
                            ProductName = "Mì Hảo Hảo Tôm Chua Cay 75g",
                            StockQuantity = 250
                        },
                        new
                        {
                            ProductId = 5,
                            Barcode = "893456789005",
                            CategoryId = 5,
                            Price = 25000m,
                            ProductName = "Nước mắm Nam Ngư Đệ Nhị 900ml",
                            StockQuantity = 50
                        },
                        new
                        {
                            ProductId = 6,
                            Barcode = "893456789006",
                            CategoryId = 6,
                            Price = 48000m,
                            ProductName = "Dầu ăn Tường An Cooking Oil 1L",
                            StockQuantity = 60
                        },
                        new
                        {
                            ProductId = 7,
                            Barcode = "893456789007",
                            CategoryId = 7,
                            Price = 160000m,
                            ProductName = "Gạo thơm ST25 túi 5kg",
                            StockQuantity = 30
                        },
                        new
                        {
                            ProductId = 8,
                            Barcode = "893456789008",
                            CategoryId = 8,
                            Price = 18000m,
                            ProductName = "Cá hộp Ba Cô Gái sốt cà 155g",
                            StockQuantity = 90
                        },
                        new
                        {
                            ProductId = 9,
                            Barcode = "893456789009",
                            CategoryId = 9,
                            Price = 28000m,
                            ProductName = "Nước rửa chén Sunlight Chanh 750g",
                            StockQuantity = 70
                        },
                        new
                        {
                            ProductId = 10,
                            Barcode = "893456789010",
                            CategoryId = 10,
                            Price = 145000m,
                            ProductName = "Dầu gội Clear Bạc Hà mát lạnh 630g",
                            StockQuantity = 40
                        },
                        new
                        {
                            ProductId = 11,
                            Barcode = "893456789011",
                            CategoryId = 11,
                            Price = 75000m,
                            ProductName = "Giấy vệ sinh Pulppy 10 cuộn 3 lớp",
                            StockQuantity = 45
                        },
                        new
                        {
                            ProductId = 12,
                            Barcode = "893456789012",
                            CategoryId = 12,
                            Price = 32000m,
                            ProductName = "Màng bọc thực phẩm Ringo 30cm",
                            StockQuantity = 50
                        },
                        new
                        {
                            ProductId = 13,
                            Barcode = "893456789013",
                            CategoryId = 13,
                            Price = 58000m,
                            ProductName = "Cà phê G7 3in1 hộp 18 gói",
                            StockQuantity = 85
                        },
                        new
                        {
                            ProductId = 14,
                            Barcode = "893456789014",
                            CategoryId = 14,
                            Price = 8000m,
                            ProductName = "Tập vở học sinh 96 trang Thiên Long",
                            StockQuantity = 200
                        },
                        new
                        {
                            ProductId = 15,
                            Barcode = "893456789015",
                            CategoryId = 15,
                            Price = 22000m,
                            ProductName = "Xúc xích tiệt trùng CP Red 175g",
                            StockQuantity = 110
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Product", b =>
                {
                    b.HasOne("MiniSupermarket.API.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
